//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCepech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alma_Imagen
    {
        public int IdImagen { get; set; }
        public string NombreImagen { get; set; }
        public byte[] Contenido { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> IdPost { get; set; }
    
        public virtual Alma_Noticia Alma_Noticia { get; set; }
    }
}
