//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCepech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alma_Noticia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alma_Noticia()
        {
            this.Alma_Aprobacion = new HashSet<Alma_Aprobacion>();
            this.Alma_Comentario = new HashSet<Alma_Comentario>();
            this.Alma_Imagen = new HashSet<Alma_Imagen>();
        }
    
        public int IdPost { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alma_Aprobacion> Alma_Aprobacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alma_Comentario> Alma_Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alma_Imagen> Alma_Imagen { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
