//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCepech.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fichas20Entities : DbContext
    {
        public Fichas20Entities()
            : base("name=Fichas20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Alma_Aprobacion> Alma_Aprobacion { get; set; }
        public virtual DbSet<Alma_Comentario> Alma_Comentario { get; set; }
        public virtual DbSet<Alma_Imagen> Alma_Imagen { get; set; }
        public virtual DbSet<Alma_Noticia> Alma_Noticia { get; set; }
    }
}
