//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCepech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Alma_Noticia = new HashSet<Alma_Noticia>();
        }
    
        public int ID_Usuario { get; set; }
        public string Username { get; set; }
        public string Nombre_Completo { get; set; }
        public bool Ejecutiva_Tlmk { get; set; }
        public byte ID_Grupo { get; set; }
        public Nullable<short> Anexo { get; set; }
        public string email { get; set; }
        public string Cargo { get; set; }
        public int ID_Sede { get; set; }
        public string Nivel { get; set; }
        public string password { get; set; }
        public byte Fallas { get; set; }
        public byte Internet { get; set; }
        public string NivelCobra { get; set; }
        public Nullable<byte> Ejecutivo_Cobranza { get; set; }
        public byte ID_TipoU { get; set; }
        public Nullable<int> Ultimo_Mensaje { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<byte> ID_Sede_Laboral { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<int> usuario_desarrollo { get; set; }
        public Nullable<int> Rut_usuario { get; set; }
        public string Dv_Rut { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> Id_Impresora_Boletas { get; set; }
        public string Ejecutiva_CCenter_Cobranza { get; set; }
        public Nullable<int> ID_perfil_Wired { get; set; }
        public Nullable<int> id_perfil_icobra { get; set; }
        public Nullable<bool> Ejecutivo_Call_Center_IP { get; set; }
        public Nullable<int> autoriza_convenio { get; set; }
        public string username_GP { get; set; }
        public Nullable<bool> subir_excel_ensayos { get; set; }
        public Nullable<int> id_sede_corporacion { get; set; }
        public Nullable<int> Usuario_Televenta { get; set; }
        public string Usuario_Dominio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alma_Noticia> Alma_Noticia { get; set; }
    }
}
